package dev.bisz.enchants.items;

import dev.bisz.enchants.SocketedVanillaItem;
import org.bukkit.Material;

/** Explicit per-material override types; shared socket behavior lives in the base class. */
public final class SocketedItemOverrides {
  private SocketedItemOverrides() {}

  public static SocketedVanillaItem create(Material material) {
    return switch (material.name()) {
      case "BOOK", "ENCHANTED_BOOK" -> new SocketedBookItem(material);
      case "BOW" -> new Bow(material); case "CROSSBOW" -> new Crossbow(material);
      case "TRIDENT" -> new Trident(material); case "FISHING_ROD" -> new FishingRod(material);
      case "TURTLE_HELMET" -> new TurtleHelmet(material); case "MACE" -> new Mace(material);
      case "STONE_SWORD" -> new StoneSword(material); case "STONE_AXE" -> new StoneAxe(material);
      case "STONE_PICKAXE" -> new StonePickaxe(material); case "STONE_SHOVEL" -> new StoneShovel(material); case "STONE_HOE" -> new StoneHoe(material);
      case "GOLDEN_HELMET" -> new GoldenHelmet(material); case "GOLDEN_CHESTPLATE" -> new GoldenChestplate(material); case "GOLDEN_LEGGINGS" -> new GoldenLeggings(material); case "GOLDEN_BOOTS" -> new GoldenBoots(material);
      case "GOLDEN_SWORD" -> new GoldenSword(material); case "GOLDEN_AXE" -> new GoldenAxe(material); case "GOLDEN_PICKAXE" -> new GoldenPickaxe(material); case "GOLDEN_SHOVEL" -> new GoldenShovel(material); case "GOLDEN_HOE" -> new GoldenHoe(material);
      case "IRON_HELMET" -> new IronHelmet(material); case "IRON_CHESTPLATE" -> new IronChestplate(material); case "IRON_LEGGINGS" -> new IronLeggings(material); case "IRON_BOOTS" -> new IronBoots(material);
      case "IRON_SWORD" -> new IronSword(material); case "IRON_AXE" -> new IronAxe(material); case "IRON_PICKAXE" -> new IronPickaxe(material); case "IRON_SHOVEL" -> new IronShovel(material); case "IRON_HOE" -> new IronHoe(material);
      case "DIAMOND_HELMET" -> new DiamondHelmet(material); case "DIAMOND_CHESTPLATE" -> new DiamondChestplate(material); case "DIAMOND_LEGGINGS" -> new DiamondLeggings(material); case "DIAMOND_BOOTS" -> new DiamondBoots(material);
      case "DIAMOND_SWORD" -> new DiamondSword(material); case "DIAMOND_AXE" -> new DiamondAxe(material); case "DIAMOND_PICKAXE" -> new DiamondPickaxe(material); case "DIAMOND_SHOVEL" -> new DiamondShovel(material); case "DIAMOND_HOE" -> new DiamondHoe(material);
      case "NETHERITE_HELMET" -> new NetheriteHelmet(material); case "NETHERITE_CHESTPLATE" -> new NetheriteChestplate(material); case "NETHERITE_LEGGINGS" -> new NetheriteLeggings(material); case "NETHERITE_BOOTS" -> new NetheriteBoots(material);
      case "NETHERITE_SWORD" -> new NetheriteSword(material); case "NETHERITE_AXE" -> new NetheriteAxe(material); case "NETHERITE_PICKAXE" -> new NetheritePickaxe(material); case "NETHERITE_SHOVEL" -> new NetheriteShovel(material); case "NETHERITE_HOE" -> new NetheriteHoe(material);
      case "LEATHER_HELMET" -> new LeatherHelmet(material); case "LEATHER_CHESTPLATE" -> new LeatherChestplate(material); case "LEATHER_LEGGINGS" -> new LeatherLeggings(material); case "LEATHER_BOOTS" -> new LeatherBoots(material);
      case "CHAINMAIL_HELMET" -> new ChainmailHelmet(material); case "CHAINMAIL_CHESTPLATE" -> new ChainmailChestplate(material); case "CHAINMAIL_LEGGINGS" -> new ChainmailLeggings(material); case "CHAINMAIL_BOOTS" -> new ChainmailBoots(material);
      case "COPPER_HELMET" -> new CopperHelmet(material); case "COPPER_CHESTPLATE" -> new CopperChestplate(material); case "COPPER_LEGGINGS" -> new CopperLeggings(material); case "COPPER_BOOTS" -> new CopperBoots(material);
      case "COPPER_SWORD" -> new CopperSword(material); case "COPPER_AXE" -> new CopperAxe(material); case "COPPER_PICKAXE" -> new CopperPickaxe(material); case "COPPER_SHOVEL" -> new CopperShovel(material); case "COPPER_HOE" -> new CopperHoe(material);
      case "STONE_SPEAR" -> new StoneSpear(material); case "COPPER_SPEAR" -> new CopperSpear(material); case "GOLDEN_SPEAR" -> new GoldenSpear(material); case "IRON_SPEAR" -> new IronSpear(material); case "DIAMOND_SPEAR" -> new DiamondSpear(material); case "NETHERITE_SPEAR" -> new NetheriteSpear(material);
      default -> new Generic(material);
    };
  }

  private abstract static class Override extends SocketedVanillaItem { Override(Material material) { super(material); } }
  private static final class Generic extends Override { Generic(Material m) { super(m); } }
  private static final class Bow extends Override { Bow(Material m) { super(m); } } private static final class Crossbow extends Override { Crossbow(Material m) { super(m); } }
  private static final class Trident extends Override { Trident(Material m) { super(m); } } private static final class FishingRod extends Override { FishingRod(Material m) { super(m); } }
  private static final class TurtleHelmet extends Override { TurtleHelmet(Material m) { super(m); } } private static final class Mace extends Override { Mace(Material m) { super(m); } }
  private static final class StoneSword extends Override { StoneSword(Material m) { super(m); } } private static final class StoneAxe extends Override { StoneAxe(Material m) { super(m); } } private static final class StonePickaxe extends Override { StonePickaxe(Material m) { super(m); } } private static final class StoneShovel extends Override { StoneShovel(Material m) { super(m); } } private static final class StoneHoe extends Override { StoneHoe(Material m) { super(m); } }
  private static final class GoldenHelmet extends Override { GoldenHelmet(Material m) { super(m); } } private static final class GoldenChestplate extends Override { GoldenChestplate(Material m) { super(m); } } private static final class GoldenLeggings extends Override { GoldenLeggings(Material m) { super(m); } } private static final class GoldenBoots extends Override { GoldenBoots(Material m) { super(m); } } private static final class GoldenSword extends Override { GoldenSword(Material m) { super(m); } } private static final class GoldenAxe extends Override { GoldenAxe(Material m) { super(m); } } private static final class GoldenPickaxe extends Override { GoldenPickaxe(Material m) { super(m); } } private static final class GoldenShovel extends Override { GoldenShovel(Material m) { super(m); } } private static final class GoldenHoe extends Override { GoldenHoe(Material m) { super(m); } }
  private static final class IronHelmet extends Override { IronHelmet(Material m) { super(m); } } private static final class IronChestplate extends Override { IronChestplate(Material m) { super(m); } } private static final class IronLeggings extends Override { IronLeggings(Material m) { super(m); } } private static final class IronBoots extends Override { IronBoots(Material m) { super(m); } } private static final class IronSword extends Override { IronSword(Material m) { super(m); } } private static final class IronAxe extends Override { IronAxe(Material m) { super(m); } } private static final class IronPickaxe extends Override { IronPickaxe(Material m) { super(m); } } private static final class IronShovel extends Override { IronShovel(Material m) { super(m); } } private static final class IronHoe extends Override { IronHoe(Material m) { super(m); } }
  private static final class DiamondHelmet extends Override { DiamondHelmet(Material m) { super(m); } } private static final class DiamondChestplate extends Override { DiamondChestplate(Material m) { super(m); } } private static final class DiamondLeggings extends Override { DiamondLeggings(Material m) { super(m); } } private static final class DiamondBoots extends Override { DiamondBoots(Material m) { super(m); } } private static final class DiamondSword extends Override { DiamondSword(Material m) { super(m); } } private static final class DiamondAxe extends Override { DiamondAxe(Material m) { super(m); } } private static final class DiamondPickaxe extends Override { DiamondPickaxe(Material m) { super(m); } } private static final class DiamondShovel extends Override { DiamondShovel(Material m) { super(m); } } private static final class DiamondHoe extends Override { DiamondHoe(Material m) { super(m); } }
  private static final class NetheriteHelmet extends Override { NetheriteHelmet(Material m) { super(m); } } private static final class NetheriteChestplate extends Override { NetheriteChestplate(Material m) { super(m); } } private static final class NetheriteLeggings extends Override { NetheriteLeggings(Material m) { super(m); } } private static final class NetheriteBoots extends Override { NetheriteBoots(Material m) { super(m); } } private static final class NetheriteSword extends Override { NetheriteSword(Material m) { super(m); } } private static final class NetheriteAxe extends Override { NetheriteAxe(Material m) { super(m); } } private static final class NetheritePickaxe extends Override { NetheritePickaxe(Material m) { super(m); } } private static final class NetheriteShovel extends Override { NetheriteShovel(Material m) { super(m); } } private static final class NetheriteHoe extends Override { NetheriteHoe(Material m) { super(m); } }
  private static final class LeatherHelmet extends Override { LeatherHelmet(Material m) { super(m); } } private static final class LeatherChestplate extends Override { LeatherChestplate(Material m) { super(m); } } private static final class LeatherLeggings extends Override { LeatherLeggings(Material m) { super(m); } } private static final class LeatherBoots extends Override { LeatherBoots(Material m) { super(m); } } private static final class ChainmailHelmet extends Override { ChainmailHelmet(Material m) { super(m); } } private static final class ChainmailChestplate extends Override { ChainmailChestplate(Material m) { super(m); } } private static final class ChainmailLeggings extends Override { ChainmailLeggings(Material m) { super(m); } } private static final class ChainmailBoots extends Override { ChainmailBoots(Material m) { super(m); } }
  private static final class CopperHelmet extends Override { CopperHelmet(Material m) { super(m); } } private static final class CopperChestplate extends Override { CopperChestplate(Material m) { super(m); } } private static final class CopperLeggings extends Override { CopperLeggings(Material m) { super(m); } } private static final class CopperBoots extends Override { CopperBoots(Material m) { super(m); } } private static final class CopperSword extends Override { CopperSword(Material m) { super(m); } } private static final class CopperAxe extends Override { CopperAxe(Material m) { super(m); } } private static final class CopperPickaxe extends Override { CopperPickaxe(Material m) { super(m); } } private static final class CopperShovel extends Override { CopperShovel(Material m) { super(m); } } private static final class CopperHoe extends Override { CopperHoe(Material m) { super(m); } }
  private static final class StoneSpear extends Override { StoneSpear(Material m) { super(m); } } private static final class CopperSpear extends Override { CopperSpear(Material m) { super(m); } } private static final class GoldenSpear extends Override { GoldenSpear(Material m) { super(m); } } private static final class IronSpear extends Override { IronSpear(Material m) { super(m); } } private static final class DiamondSpear extends Override { DiamondSpear(Material m) { super(m); } } private static final class NetheriteSpear extends Override { NetheriteSpear(Material m) { super(m); } }
}
