name: "worldgen"
version: "26.2"
main: dev.bisz.worldgen.WorldGenPlugin
api-version: '1.20'
authors: ["Intestide"]
depend: [Bundler]
softdepend: [WorldEdit]
permissions:
  worldgen.admin:
    description: Manage world generation, regeneration, and POIs.
    default: op
