name: Items
version: 2.0.0-SNAPSHOT
main: dev.bisz.items.ItemsPlugin
api-version: "1.20"
authors: [BisZ]
depend: [Bundler]
permissions:
  items.debug:
    description: Allows ItemLib inventory debugging commands.
    default: op
