debug: false
display:
  custom-font: true
  damage-indicators: true
  xp-action-bar: true
server:
  resource-pack:
    enabled: true
    port: 9090
    url: ""
    required: true
xp:
  points-per-level: 100
cost:
  multiplier: 1.0
  refund-percent: 80
enchanting:
  lapis-cost: 3
